### Post request to create a user.
POST http://localhost:4004/api/clients/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email": "test_user3@test.com",
  "address": "123 Test-Request Ave, 493201, WA, USA.",
  "dateOfBirth": "2000-01-01",
  "registeredDate": "2025-01-01"
}