### Post request to change password.

### Requires a token.
### Requires a UserRequestDto: email, password (This is the new password.)
POST http://localhost:4004/api/auth/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password": "java_4_life"
}
